[package]
name = "replaceable_implementations"
version = "0.1.0"
edition = "2024"
description = "Allows procedural macros to replace implementations."
license = "MIT OR Apache-2.0"
repository = "https://github.com/coolcatcoder/replaceable_implementations"
keywords = ["linkage","registration"]
categories = []
readme = "README.md"

[dependencies]
syn = {version = "2.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"